# fixExportsNAS.yaml
---
- name: Fix NAS Exports
  gather_facts: true
  hosts: NAS
  become: false
  tasks:
    - name: Execute uptime command
      command: uptime
      register: uptime_result
    - debug: var=uptime_result.stdout_lines

    - name: Check exports
      command: cat /etc/exports
      register: exports_result
    - debug: var=exports_result.stdout_lines
